FROM python:3.8.11-slim-buster

RUN apt-get update; \
	apt-get install -y --no-install-recommends \
		ffmpeg

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app
RUN pip install -r requirements.txt

ENTRYPOINT [ "flask" ]
CMD ["run", "--host=0.0.0.0", "--port=8080"]