FROM python:3.8.11-slim-buster

RUN apt-get update; \
	apt-get install -y --no-install-recommends \
		ffmpeg

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app
RUN pip install -r requirements.txt

RUN pip install gunicorn==20.0.4
EXPOSE 8080

CMD ["/bin/bash"]
ENTRYPOINT gunicorn --chdir /usr/src/app app:app -w 2 --threads 2 -b 0.0.0.0:8080