FROM python:3.8.11-slim-buster

RUN apt-get update; \
	apt-get install -y --no-install-recommends \
		ffmpeg

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app
RUN pip install -r requirements.txt

CMD ["/bin/bash"]
ENTRYPOINT python app.py